apiVersion: v1
kind: Pod
metadata:
  name: calico-api-server
spec:
  containers:
    - name: api-server
      image: calico-api-server:latest
      ports:
        - containerPort: 80
      env:
        - name: ETCD_AUTHORITY
          value: "10.96.0.101:32379"

